# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Disability(BaseModel):
    disability_code: typing.Optional[Literal["aut", "db", "dd", "emn", "hi", "id", "md", "oi", "other", "ohi", "sld", "sli", "tbi", "vi"]] = Field(None, alias='disability_code')

    disability_status: typing.Optional[Literal["Y", "N", ""]] = Field(None, alias='disability_status')

    disability_type: typing.Optional[Literal["Autism", "Deaf-blindness", "Developmental delay", "Emotional disturbance", "Hearing impairment", "Intellectual Disability", "Multiple disabilities", "Orthopedic impairment", "Other", "Other health impairment", "Specific learning disability", "Speech or language impairment", "Traumatic brain injury", "Visual impairment"]] = Field(None, alias='disability_type')
    class Config:
        arbitrary_types_allowed = True
