# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.district_contact import DistrictContact
from clever_python_sdk.pydantic.district_login_methods import DistrictLoginMethods

class District(BaseModel):
    district_contact: typing.Optional[DistrictContact] = Field(None, alias='district_contact')

    error: typing.Optional[str] = Field(None, alias='error')

    id: typing.Optional[str] = Field(None, alias='id')

    last_sync: typing.Optional[typing.Optional[str]] = Field(None, alias='last_sync')

    launch_date: typing.Optional[date] = Field(None, alias='launch_date')

    lms_state: typing.Optional[Literal["matching_in_progress", "error", "disconnected", "", "success"]] = Field(None, alias='lms_state')

    login_methods: typing.Optional[DistrictLoginMethods] = Field(None, alias='login_methods')

    mdr_number: typing.Optional[typing.Optional[str]] = Field(None, alias='mdr_number')

    name: typing.Optional[str] = Field(None, alias='name')

    nces_id: typing.Optional[typing.Optional[str]] = Field(None, alias='nces_id')

    pause_end: typing.Optional[typing.Optional[str]] = Field(None, alias='pause_end')

    pause_start: typing.Optional[typing.Optional[str]] = Field(None, alias='pause_start')

    portal_url: typing.Optional[str] = Field(None, alias='portal_url')

    sis_type: typing.Optional[str] = Field(None, alias='sis_type')

    state: typing.Optional[Literal["running", "pending", "error", "paused", "", "success"]] = Field(None, alias='state')
    class Config:
        arbitrary_types_allowed = True
