# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Location(BaseModel):
    address: typing.Optional[typing.Optional[str]] = Field(None, alias='address')

    city: typing.Optional[typing.Optional[str]] = Field(None, alias='city')

    lat: typing.Optional[typing.Optional[str]] = Field(None, alias='lat')

    lon: typing.Optional[typing.Optional[str]] = Field(None, alias='lon')

    state: typing.Optional[typing.Optional[str]] = Field(None, alias='state')

    zip: typing.Optional[typing.Optional[str]] = Field(None, alias='zip')
    class Config:
        arbitrary_types_allowed = True
