# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.link import Link
from clever_python_sdk.pydantic.resource_response import ResourceResponse

class ResourcesResponse(BaseModel):
    data: typing.Optional[typing.List[ResourceResponse]] = Field(None, alias='data')

    links: typing.Optional[typing.List[Link]] = Field(None, alias='links')
    class Config:
        arbitrary_types_allowed = True
