# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.resource_roles import ResourceRoles

class Resource(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    created: typing.Optional[datetime] = Field(None, alias='created')

    district: typing.Optional[str] = Field(None, alias='district')

    id: typing.Optional[str] = Field(None, alias='id')

    resource_id: typing.Optional[str] = Field(None, alias='resource_id')

    roles: typing.Optional[ResourceRoles] = Field(None, alias='roles')

    updated: typing.Optional[datetime] = Field(None, alias='updated')
    class Config:
        arbitrary_types_allowed = True
