# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.contact import Contact
from clever_python_sdk.pydantic.district_admin import DistrictAdmin
from clever_python_sdk.pydantic.staff import Staff
from clever_python_sdk.pydantic.student import Student
from clever_python_sdk.pydantic.teacher import Teacher

class Roles(BaseModel):
    contact: typing.Optional[Contact] = Field(None, alias='contact')

    district_admin: typing.Optional[DistrictAdmin] = Field(None, alias='district_admin')

    staff: typing.Optional[Staff] = Field(None, alias='staff')

    student: typing.Optional[Student] = Field(None, alias='student')

    teacher: typing.Optional[Teacher] = Field(None, alias='teacher')
    class Config:
        arbitrary_types_allowed = True
