# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.credentials import Credentials
from clever_python_sdk.pydantic.staff_roles import StaffRoles
from clever_python_sdk.pydantic.staff_schools import StaffSchools

class Staff(BaseModel):
    title: typing.Optional[typing.Optional[str]] = Field(None, alias='title')

    credentials: typing.Optional[Credentials] = Field(None, alias='credentials')

    department: typing.Optional[typing.Optional[str]] = Field(None, alias='department')

    ext: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='ext')

    legacy_id: typing.Optional[str] = Field(None, alias='legacy_id')

    roles: typing.Optional[StaffRoles] = Field(None, alias='roles')

    schools: typing.Optional[StaffSchools] = Field(None, alias='schools')

    staff_id: typing.Optional[str] = Field(None, alias='staff_id')
    class Config:
        arbitrary_types_allowed = True
