# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class StudentRelationship(BaseModel):
    relationship: typing.Optional[Literal["Parent", "Grandparent", "Self", "Aunt/Uncle", "Sibling", "Other", ""]] = Field(None, alias='relationship')

    student: typing.Optional[str] = Field(None, alias='student')

    type: typing.Optional[Literal["Parent/Guardian", "Emergency", "Primary", "Secondary", "Family", "Other", ""]] = Field(None, alias='type')
    class Config:
        arbitrary_types_allowed = True
