# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from clever_python_sdk.pydantic.name import Name
from clever_python_sdk.pydantic.roles import Roles

class User(BaseModel):
    created: typing.Optional[str] = Field(None, alias='created')

    district: typing.Optional[str] = Field(None, alias='district')

    email: typing.Optional[typing.Optional[str]] = Field(None, alias='email')

    id: typing.Optional[str] = Field(None, alias='id')

    last_modified: typing.Optional[str] = Field(None, alias='last_modified')

    name: typing.Optional[Name] = Field(None, alias='name')

    roles: typing.Optional[Roles] = Field(None, alias='roles')
    class Config:
        arbitrary_types_allowed = True
