# coding: utf-8
"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from clever_python_sdk.client_custom import ClientCustom
from clever_python_sdk.configuration import Configuration
from clever_python_sdk.api_client import ApiClient
from clever_python_sdk.type_util import copy_signature
from clever_python_sdk.apis.tags.courses_api import CoursesApi
from clever_python_sdk.apis.tags.districts_api import DistrictsApi
from clever_python_sdk.apis.tags.resources_api import ResourcesApi
from clever_python_sdk.apis.tags.schools_api import SchoolsApi
from clever_python_sdk.apis.tags.sections_api import SectionsApi
from clever_python_sdk.apis.tags.terms_api import TermsApi
from clever_python_sdk.apis.tags.users_api import UsersApi



class Clever(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.courses: CoursesApi = CoursesApi(api_client)
        self.districts: DistrictsApi = DistrictsApi(api_client)
        self.resources: ResourcesApi = ResourcesApi(api_client)
        self.schools: SchoolsApi = SchoolsApi(api_client)
        self.sections: SectionsApi = SectionsApi(api_client)
        self.terms: TermsApi = TermsApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
