# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import clever_python_sdk
from clever_python_sdk.model.schools_response import SchoolsResponse
from clever_python_sdk import configuration


class TestSchoolsResponse(unittest.TestCase):
    """SchoolsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
