# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from clever_python_sdk import schemas  # noqa: F401


class School(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            created = schemas.StrSchema
            district = schemas.StrSchema
            ext = schemas.DictSchema
            
            
            class high_grade(
                schemas.EnumBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "InfantToddler": "INFANT_TODDLER",
                        "Preschool": "PRESCHOOL",
                        "PreKindergarten": "PRE_KINDERGARTEN",
                        "TransitionalKindergarten": "TRANSITIONAL_KINDERGARTEN",
                        "Kindergarten": "KINDERGARTEN",
                        "1": "POSITIVE_1",
                        "2": "POSITIVE_2",
                        "3": "POSITIVE_3",
                        "4": "POSITIVE_4",
                        "5": "POSITIVE_5",
                        "6": "POSITIVE_6",
                        "7": "POSITIVE_7",
                        "8": "POSITIVE_8",
                        "9": "POSITIVE_9",
                        "10": "POSITIVE_10",
                        "11": "POSITIVE_11",
                        "12": "POSITIVE_12",
                        "13": "POSITIVE_13",
                        "PostGraduate": "POST_GRADUATE",
                        "Ungraded": "UNGRADED",
                        "Other": "OTHER",
                        "": "EMPTY",
                    }
                
                @schemas.classproperty
                def INFANT_TODDLER(cls):
                    return cls("InfantToddler")
                
                @schemas.classproperty
                def PRESCHOOL(cls):
                    return cls("Preschool")
                
                @schemas.classproperty
                def PRE_KINDERGARTEN(cls):
                    return cls("PreKindergarten")
                
                @schemas.classproperty
                def TRANSITIONAL_KINDERGARTEN(cls):
                    return cls("TransitionalKindergarten")
                
                @schemas.classproperty
                def KINDERGARTEN(cls):
                    return cls("Kindergarten")
                
                @schemas.classproperty
                def POSITIVE_1(cls):
                    return cls("1")
                
                @schemas.classproperty
                def POSITIVE_2(cls):
                    return cls("2")
                
                @schemas.classproperty
                def POSITIVE_3(cls):
                    return cls("3")
                
                @schemas.classproperty
                def POSITIVE_4(cls):
                    return cls("4")
                
                @schemas.classproperty
                def POSITIVE_5(cls):
                    return cls("5")
                
                @schemas.classproperty
                def POSITIVE_6(cls):
                    return cls("6")
                
                @schemas.classproperty
                def POSITIVE_7(cls):
                    return cls("7")
                
                @schemas.classproperty
                def POSITIVE_8(cls):
                    return cls("8")
                
                @schemas.classproperty
                def POSITIVE_9(cls):
                    return cls("9")
                
                @schemas.classproperty
                def POSITIVE_10(cls):
                    return cls("10")
                
                @schemas.classproperty
                def POSITIVE_11(cls):
                    return cls("11")
                
                @schemas.classproperty
                def POSITIVE_12(cls):
                    return cls("12")
                
                @schemas.classproperty
                def POSITIVE_13(cls):
                    return cls("13")
                
                @schemas.classproperty
                def POST_GRADUATE(cls):
                    return cls("PostGraduate")
                
                @schemas.classproperty
                def UNGRADED(cls):
                    return cls("Ungraded")
                
                @schemas.classproperty
                def OTHER(cls):
                    return cls("Other")
                
                @schemas.classproperty
                def EMPTY(cls):
                    return cls("")
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'high_grade':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            id = schemas.StrSchema
            last_modified = schemas.StrSchema
        
            @staticmethod
            def location() -> typing.Type['Location']:
                return Location
            
            
            class low_grade(
                schemas.EnumBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "InfantToddler": "INFANT_TODDLER",
                        "Preschool": "PRESCHOOL",
                        "PreKindergarten": "PRE_KINDERGARTEN",
                        "TransitionalKindergarten": "TRANSITIONAL_KINDERGARTEN",
                        "Kindergarten": "KINDERGARTEN",
                        "1": "POSITIVE_1",
                        "2": "POSITIVE_2",
                        "3": "POSITIVE_3",
                        "4": "POSITIVE_4",
                        "5": "POSITIVE_5",
                        "6": "POSITIVE_6",
                        "7": "POSITIVE_7",
                        "8": "POSITIVE_8",
                        "9": "POSITIVE_9",
                        "10": "POSITIVE_10",
                        "11": "POSITIVE_11",
                        "12": "POSITIVE_12",
                        "13": "POSITIVE_13",
                        "PostGraduate": "POST_GRADUATE",
                        "Ungraded": "UNGRADED",
                        "Other": "OTHER",
                        "": "EMPTY",
                    }
                
                @schemas.classproperty
                def INFANT_TODDLER(cls):
                    return cls("InfantToddler")
                
                @schemas.classproperty
                def PRESCHOOL(cls):
                    return cls("Preschool")
                
                @schemas.classproperty
                def PRE_KINDERGARTEN(cls):
                    return cls("PreKindergarten")
                
                @schemas.classproperty
                def TRANSITIONAL_KINDERGARTEN(cls):
                    return cls("TransitionalKindergarten")
                
                @schemas.classproperty
                def KINDERGARTEN(cls):
                    return cls("Kindergarten")
                
                @schemas.classproperty
                def POSITIVE_1(cls):
                    return cls("1")
                
                @schemas.classproperty
                def POSITIVE_2(cls):
                    return cls("2")
                
                @schemas.classproperty
                def POSITIVE_3(cls):
                    return cls("3")
                
                @schemas.classproperty
                def POSITIVE_4(cls):
                    return cls("4")
                
                @schemas.classproperty
                def POSITIVE_5(cls):
                    return cls("5")
                
                @schemas.classproperty
                def POSITIVE_6(cls):
                    return cls("6")
                
                @schemas.classproperty
                def POSITIVE_7(cls):
                    return cls("7")
                
                @schemas.classproperty
                def POSITIVE_8(cls):
                    return cls("8")
                
                @schemas.classproperty
                def POSITIVE_9(cls):
                    return cls("9")
                
                @schemas.classproperty
                def POSITIVE_10(cls):
                    return cls("10")
                
                @schemas.classproperty
                def POSITIVE_11(cls):
                    return cls("11")
                
                @schemas.classproperty
                def POSITIVE_12(cls):
                    return cls("12")
                
                @schemas.classproperty
                def POSITIVE_13(cls):
                    return cls("13")
                
                @schemas.classproperty
                def POST_GRADUATE(cls):
                    return cls("PostGraduate")
                
                @schemas.classproperty
                def UNGRADED(cls):
                    return cls("Ungraded")
                
                @schemas.classproperty
                def OTHER(cls):
                    return cls("Other")
                
                @schemas.classproperty
                def EMPTY(cls):
                    return cls("")
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'low_grade':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class mdr_number(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'mdr_number':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            name = schemas.StrSchema
            
            
            class nces_id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'nces_id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class phone(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'phone':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def principal() -> typing.Type['Principal']:
                return Principal
            school_number = schemas.StrSchema
            sis_id = schemas.StrSchema
            
            
            class state_id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'state_id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "created": created,
                "district": district,
                "ext": ext,
                "high_grade": high_grade,
                "id": id,
                "last_modified": last_modified,
                "location": location,
                "low_grade": low_grade,
                "mdr_number": mdr_number,
                "name": name,
                "nces_id": nces_id,
                "phone": phone,
                "principal": principal,
                "school_number": school_number,
                "sis_id": sis_id,
                "state_id": state_id,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created"]) -> MetaOapg.properties.created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["district"]) -> MetaOapg.properties.district: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ext"]) -> MetaOapg.properties.ext: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["high_grade"]) -> MetaOapg.properties.high_grade: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_modified"]) -> MetaOapg.properties.last_modified: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location"]) -> 'Location': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["low_grade"]) -> MetaOapg.properties.low_grade: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mdr_number"]) -> MetaOapg.properties.mdr_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nces_id"]) -> MetaOapg.properties.nces_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["principal"]) -> 'Principal': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["school_number"]) -> MetaOapg.properties.school_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sis_id"]) -> MetaOapg.properties.sis_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state_id"]) -> MetaOapg.properties.state_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["created", "district", "ext", "high_grade", "id", "last_modified", "location", "low_grade", "mdr_number", "name", "nces_id", "phone", "principal", "school_number", "sis_id", "state_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created"]) -> typing.Union[MetaOapg.properties.created, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["district"]) -> typing.Union[MetaOapg.properties.district, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ext"]) -> typing.Union[MetaOapg.properties.ext, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["high_grade"]) -> typing.Union[MetaOapg.properties.high_grade, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_modified"]) -> typing.Union[MetaOapg.properties.last_modified, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location"]) -> typing.Union['Location', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["low_grade"]) -> typing.Union[MetaOapg.properties.low_grade, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mdr_number"]) -> typing.Union[MetaOapg.properties.mdr_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nces_id"]) -> typing.Union[MetaOapg.properties.nces_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> typing.Union[MetaOapg.properties.phone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["principal"]) -> typing.Union['Principal', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["school_number"]) -> typing.Union[MetaOapg.properties.school_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sis_id"]) -> typing.Union[MetaOapg.properties.sis_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state_id"]) -> typing.Union[MetaOapg.properties.state_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["created", "district", "ext", "high_grade", "id", "last_modified", "location", "low_grade", "mdr_number", "name", "nces_id", "phone", "principal", "school_number", "sis_id", "state_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        created: typing.Union[MetaOapg.properties.created, str, schemas.Unset] = schemas.unset,
        district: typing.Union[MetaOapg.properties.district, str, schemas.Unset] = schemas.unset,
        ext: typing.Union[MetaOapg.properties.ext, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        high_grade: typing.Union[MetaOapg.properties.high_grade, None, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        last_modified: typing.Union[MetaOapg.properties.last_modified, str, schemas.Unset] = schemas.unset,
        location: typing.Union['Location', schemas.Unset] = schemas.unset,
        low_grade: typing.Union[MetaOapg.properties.low_grade, None, str, schemas.Unset] = schemas.unset,
        mdr_number: typing.Union[MetaOapg.properties.mdr_number, None, str, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        nces_id: typing.Union[MetaOapg.properties.nces_id, None, str, schemas.Unset] = schemas.unset,
        phone: typing.Union[MetaOapg.properties.phone, None, str, schemas.Unset] = schemas.unset,
        principal: typing.Union['Principal', schemas.Unset] = schemas.unset,
        school_number: typing.Union[MetaOapg.properties.school_number, str, schemas.Unset] = schemas.unset,
        sis_id: typing.Union[MetaOapg.properties.sis_id, str, schemas.Unset] = schemas.unset,
        state_id: typing.Union[MetaOapg.properties.state_id, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'School':
        return super().__new__(
            cls,
            *args,
            created=created,
            district=district,
            ext=ext,
            high_grade=high_grade,
            id=id,
            last_modified=last_modified,
            location=location,
            low_grade=low_grade,
            mdr_number=mdr_number,
            name=name,
            nces_id=nces_id,
            phone=phone,
            principal=principal,
            school_number=school_number,
            sis_id=sis_id,
            state_id=state_id,
            _configuration=_configuration,
            **kwargs,
        )

from clever_python_sdk.model.location import Location
from clever_python_sdk.model.principal import Principal
