# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.courses_id_district.get import GetDistrict
from clever_python_sdk.paths.courses.get import GetList
from clever_python_sdk.paths.courses_id_resources.get import GetResources
from clever_python_sdk.paths.courses_id_schools.get import GetSchools
from clever_python_sdk.paths.courses_id_sections.get import GetSections
from clever_python_sdk.paths.courses_id.get import GetSpecificCourse
from clever_python_sdk.apis.tags.courses_api_raw import CoursesApiRaw


class CoursesApi(
    GetDistrict,
    GetList,
    GetResources,
    GetSchools,
    GetSections,
    GetSpecificCourse,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CoursesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CoursesApiRaw(api_client)
