# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.courses_id_district.get import GetDistrictRaw
from clever_python_sdk.paths.courses.get import GetListRaw
from clever_python_sdk.paths.courses_id_resources.get import GetResourcesRaw
from clever_python_sdk.paths.courses_id_schools.get import GetSchoolsRaw
from clever_python_sdk.paths.courses_id_sections.get import GetSectionsRaw
from clever_python_sdk.paths.courses_id.get import GetSpecificCourseRaw


class CoursesApiRaw(
    GetDistrictRaw,
    GetListRaw,
    GetResourcesRaw,
    GetSchoolsRaw,
    GetSectionsRaw,
    GetSpecificCourseRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
