# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.districts.get import GetListRaw
from clever_python_sdk.paths.districts_id.get import GetSpecificDistrictRaw


class DistrictsApiRaw(
    GetListRaw,
    GetSpecificDistrictRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
