# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.resources_id.get import GetById
from clever_python_sdk.paths.resources_id_courses.get import GetCourses
from clever_python_sdk.paths.resources.get import GetList
from clever_python_sdk.paths.resources_id_users.get import GetUsers
from clever_python_sdk.paths.resources_id_sections.get import ListSections
from clever_python_sdk.apis.tags.resources_api_raw import ResourcesApiRaw


class ResourcesApi(
    GetById,
    GetCourses,
    GetList,
    GetUsers,
    ListSections,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ResourcesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ResourcesApiRaw(api_client)
