# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.resources_id.get import GetByIdRaw
from clever_python_sdk.paths.resources_id_courses.get import GetCoursesRaw
from clever_python_sdk.paths.resources.get import GetListRaw
from clever_python_sdk.paths.resources_id_users.get import GetUsersRaw
from clever_python_sdk.paths.resources_id_sections.get import ListSectionsRaw


class ResourcesApiRaw(
    GetByIdRaw,
    GetCoursesRaw,
    GetListRaw,
    GetUsersRaw,
    ListSectionsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
