# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.schools_id_courses.get import GetCourses
from clever_python_sdk.paths.schools_id_district.get import GetDistrict
from clever_python_sdk.paths.schools_id_sections.get import GetSections
from clever_python_sdk.paths.schools_id.get import GetSpecificSchool
from clever_python_sdk.paths.schools_id_terms.get import GetTerms
from clever_python_sdk.paths.schools_id_users.get import GetUsers
from clever_python_sdk.paths.schools.get import List
from clever_python_sdk.apis.tags.schools_api_raw import SchoolsApiRaw


class SchoolsApi(
    GetCourses,
    GetDistrict,
    GetSections,
    GetSpecificSchool,
    GetTerms,
    GetUsers,
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SchoolsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SchoolsApiRaw(api_client)
