# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.sections_id_course.get import GetCourseRaw
from clever_python_sdk.paths.sections_id_district.get import GetDistrictRaw
from clever_python_sdk.paths.sections.get import GetListRaw
from clever_python_sdk.paths.sections_id_resources.get import GetResourcesRaw
from clever_python_sdk.paths.sections_id_school.get import GetSchoolRaw
from clever_python_sdk.paths.sections_id.get import GetSpecificSectionRaw
from clever_python_sdk.paths.sections_id_term.get import GetTermRaw
from clever_python_sdk.paths.sections_id_users.get import GetUsersRaw


class SectionsApiRaw(
    GetCourseRaw,
    GetDistrictRaw,
    GetListRaw,
    GetResourcesRaw,
    GetSchoolRaw,
    GetSpecificSectionRaw,
    GetTermRaw,
    GetUsersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
