# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.sections_id_course.get import GetCourse
from clever_python_sdk.paths.sections_id_district.get import GetDistrict
from clever_python_sdk.paths.sections.get import GetList
from clever_python_sdk.paths.sections_id_resources.get import GetResources
from clever_python_sdk.paths.sections_id_school.get import GetSchool
from clever_python_sdk.paths.sections_id.get import GetSpecificSection
from clever_python_sdk.paths.sections_id_term.get import GetTerm
from clever_python_sdk.paths.sections_id_users.get import GetUsers
from clever_python_sdk.apis.tags.sections_api_raw import SectionsApiRaw


class SectionsApi(
    GetCourse,
    GetDistrict,
    GetList,
    GetResources,
    GetSchool,
    GetSpecificSection,
    GetTerm,
    GetUsers,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SectionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SectionsApiRaw(api_client)
