# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.terms_id_district.get import GetDistrictByIdRaw
from clever_python_sdk.paths.terms.get import GetListRaw
from clever_python_sdk.paths.terms_id_schools.get import GetSchoolsForTermRaw
from clever_python_sdk.paths.terms_id_sections.get import GetSectionsRaw
from clever_python_sdk.paths.terms_id.get import GetSpecificTermRaw


class TermsApiRaw(
    GetDistrictByIdRaw,
    GetListRaw,
    GetSchoolsForTermRaw,
    GetSectionsRaw,
    GetSpecificTermRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
