# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.terms_id_district.get import GetDistrictById
from clever_python_sdk.paths.terms.get import GetList
from clever_python_sdk.paths.terms_id_schools.get import GetSchoolsForTerm
from clever_python_sdk.paths.terms_id_sections.get import GetSections
from clever_python_sdk.paths.terms_id.get import GetSpecificTerm
from clever_python_sdk.apis.tags.terms_api_raw import TermsApiRaw


class TermsApi(
    GetDistrictById,
    GetList,
    GetSchoolsForTerm,
    GetSections,
    GetSpecificTerm,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TermsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TermsApiRaw(api_client)
