# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.users_id_district.get import GetDistrictRaw
from clever_python_sdk.paths.users.get import GetListRaw
from clever_python_sdk.paths.users_id_mycontacts.get import GetMyContactsRaw
from clever_python_sdk.paths.users_id_resources.get import GetResourcesRaw
from clever_python_sdk.paths.users_id_schools.get import GetSchoolsRaw
from clever_python_sdk.paths.users_id_sections.get import GetSectionsRaw
from clever_python_sdk.paths.users_id_mystudents.get import GetStudentUsersRaw
from clever_python_sdk.paths.users_id_myteachers.get import GetTeachersForUserRaw
from clever_python_sdk.paths.users_id.get import GetUserByIdRaw


class UsersApiRaw(
    GetDistrictRaw,
    GetListRaw,
    GetMyContactsRaw,
    GetResourcesRaw,
    GetSchoolsRaw,
    GetSectionsRaw,
    GetStudentUsersRaw,
    GetTeachersForUserRaw,
    GetUserByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
