# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from clever_python_sdk.paths.users_id_district.get import GetDistrict
from clever_python_sdk.paths.users.get import GetList
from clever_python_sdk.paths.users_id_mycontacts.get import GetMyContacts
from clever_python_sdk.paths.users_id_resources.get import GetResources
from clever_python_sdk.paths.users_id_schools.get import GetSchools
from clever_python_sdk.paths.users_id_sections.get import GetSections
from clever_python_sdk.paths.users_id_mystudents.get import GetStudentUsers
from clever_python_sdk.paths.users_id_myteachers.get import GetTeachersForUser
from clever_python_sdk.paths.users_id.get import GetUserById
from clever_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    GetDistrict,
    GetList,
    GetMyContacts,
    GetResources,
    GetSchools,
    GetSections,
    GetStudentUsers,
    GetTeachersForUser,
    GetUserById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
