# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import clever_python_sdk
from clever_python_sdk.paths.sections_id_term import get
from clever_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestSectionsIdTerm(ApiTestMixin, unittest.TestCase):
    """
    SectionsIdTerm unit test stubs
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
