# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from clever_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    COURSES = "/courses"
    COURSES_ID = "/courses/{id}"
    COURSES_ID_DISTRICT = "/courses/{id}/district"
    COURSES_ID_RESOURCES = "/courses/{id}/resources"
    COURSES_ID_SCHOOLS = "/courses/{id}/schools"
    COURSES_ID_SECTIONS = "/courses/{id}/sections"
    DISTRICTS = "/districts"
    DISTRICTS_ID = "/districts/{id}"
    RESOURCES = "/resources"
    RESOURCES_ID = "/resources/{id}"
    RESOURCES_ID_COURSES = "/resources/{id}/courses"
    RESOURCES_ID_SECTIONS = "/resources/{id}/sections"
    RESOURCES_ID_USERS = "/resources/{id}/users"
    SCHOOLS = "/schools"
    SCHOOLS_ID = "/schools/{id}"
    SCHOOLS_ID_COURSES = "/schools/{id}/courses"
    SCHOOLS_ID_DISTRICT = "/schools/{id}/district"
    SCHOOLS_ID_SECTIONS = "/schools/{id}/sections"
    SCHOOLS_ID_TERMS = "/schools/{id}/terms"
    SCHOOLS_ID_USERS = "/schools/{id}/users"
    SECTIONS = "/sections"
    SECTIONS_ID = "/sections/{id}"
    SECTIONS_ID_COURSE = "/sections/{id}/course"
    SECTIONS_ID_DISTRICT = "/sections/{id}/district"
    SECTIONS_ID_RESOURCES = "/sections/{id}/resources"
    SECTIONS_ID_SCHOOL = "/sections/{id}/school"
    SECTIONS_ID_TERM = "/sections/{id}/term"
    SECTIONS_ID_USERS = "/sections/{id}/users"
    TERMS = "/terms"
    TERMS_ID = "/terms/{id}"
    TERMS_ID_DISTRICT = "/terms/{id}/district"
    TERMS_ID_SCHOOLS = "/terms/{id}/schools"
    TERMS_ID_SECTIONS = "/terms/{id}/sections"
    USERS = "/users"
    USERS_ID = "/users/{id}"
    USERS_ID_DISTRICT = "/users/{id}/district"
    USERS_ID_MYCONTACTS = "/users/{id}/mycontacts"
    USERS_ID_MYSTUDENTS = "/users/{id}/mystudents"
    USERS_ID_MYTEACHERS = "/users/{id}/myteachers"
    USERS_ID_RESOURCES = "/users/{id}/resources"
    USERS_ID_SCHOOLS = "/users/{id}/schools"
    USERS_ID_SECTIONS = "/users/{id}/sections"
