# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.course_response import CourseResponse
from clever_python_sdk.type.link import Link

class RequiredCoursesResponse(TypedDict):
    pass

class OptionalCoursesResponse(TypedDict, total=False):
    data: typing.List[CourseResponse]

    links: typing.List[Link]

class CoursesResponse(RequiredCoursesResponse, OptionalCoursesResponse):
    pass
