# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLocation(TypedDict):
    pass

class OptionalLocation(TypedDict, total=False):
    address: typing.Optional[str]

    city: typing.Optional[str]

    lat: typing.Optional[str]

    lon: typing.Optional[str]

    state: typing.Optional[str]

    zip: typing.Optional[str]

class Location(RequiredLocation, OptionalLocation):
    pass
