# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.contact import Contact
from clever_python_sdk.type.district_admin import DistrictAdmin
from clever_python_sdk.type.staff import Staff
from clever_python_sdk.type.student import Student
from clever_python_sdk.type.teacher import Teacher

class RequiredRoles(TypedDict):
    pass

class OptionalRoles(TypedDict, total=False):
    contact: Contact

    district_admin: DistrictAdmin

    staff: Staff

    student: Student

    teacher: Teacher

class Roles(RequiredRoles, OptionalRoles):
    pass
