# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.location import Location
from clever_python_sdk.type.principal import Principal

class RequiredSchool(TypedDict):
    pass

class OptionalSchool(TypedDict, total=False):
    created: str

    district: str

    ext: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    high_grade: typing.Optional[str]

    id: str

    last_modified: str

    location: Location

    low_grade: typing.Optional[str]

    mdr_number: typing.Optional[str]

    name: str

    nces_id: typing.Optional[str]

    phone: typing.Optional[str]

    principal: Principal

    school_number: str

    sis_id: str

    state_id: typing.Optional[str]

class School(RequiredSchool, OptionalSchool):
    pass
