# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.credentials import Credentials
from clever_python_sdk.type.staff_roles import StaffRoles
from clever_python_sdk.type.staff_schools import StaffSchools

class RequiredStaff(TypedDict):
    pass

class OptionalStaff(TypedDict, total=False):
    title: typing.Optional[str]

    credentials: Credentials

    department: typing.Optional[str]

    ext: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    legacy_id: str

    roles: StaffRoles

    schools: StaffSchools

    staff_id: str

class Staff(RequiredStaff, OptionalStaff):
    pass
