# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.credentials import Credentials
from clever_python_sdk.type.disability import Disability
from clever_python_sdk.type.location import Location
from clever_python_sdk.type.preferred_name import PreferredName
from clever_python_sdk.type.school_enrollment import SchoolEnrollment
from clever_python_sdk.type.student_schools import StudentSchools

class RequiredStudent(TypedDict):
    pass

class OptionalStudent(TypedDict, total=False):
    created: str

    credentials: Credentials

    disability: Disability

    dob: typing.Optional[str]

    ell_status: typing.Optional[str]

    enrollments: typing.List[SchoolEnrollment]

    ext: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    frl_status: typing.Optional[str]

    gender: typing.Optional[str]

    gifted_status: typing.Optional[str]

    grade: typing.Optional[str]

    graduation_year: typing.Optional[str]

    hispanic_ethnicity: typing.Optional[str]

    home_language: typing.Optional[str]

    home_language_code: typing.Optional[str]

    iep_status: typing.Optional[str]

    last_modified: str

    legacy_id: str

    location: Location

    preferred_name: PreferredName

    race: typing.Optional[str]

    school: str

    schools: StudentSchools

    section_504_status: typing.Optional[str]

    sis_id: str

    state_id: typing.Optional[str]

    student_number: typing.Optional[str]

class Student(RequiredStudent, OptionalStudent):
    pass
