# coding: utf-8

"""
    Data API

    Serves the Clever Data API

    The version of the OpenAPI document: 3.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from clever_python_sdk.type.credentials import Credentials
from clever_python_sdk.type.name import Name
from clever_python_sdk.type.teacher_schools import TeacherSchools

class RequiredTeacher(TypedDict):
    pass

class OptionalTeacher(TypedDict, total=False):
    title: typing.Optional[str]

    created: str

    credentials: Credentials

    district: str

    ext: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    last_modified: str

    legacy_id: str

    name: Name

    school: str

    schools: TeacherSchools

    sis_id: str

    state_id: typing.Optional[str]

    teacher_number: typing.Optional[str]

class Teacher(RequiredTeacher, OptionalTeacher):
    pass
